### ISSUE TITLE
Provide dockerization option

### ISSUE THREAD

**Issue by erik-whiting** [erik-whiting/test_site#7]
Provide some Dockerfile and docker-compose scripts that will let users run this test bed with containers if they so choose.

**Comment by MarcinGladkowski** [comment]
Hi! If I can I will take it.

**Comment by erik-whiting** [comment]
> Hi! If I can I will take it. 

Heck yeah! Let me know if you have any questions

**Comment by MarcinGladkowski** [comment]
Thanks. You can close this Issue.
